DROP TABLE IF EXISTS TABLE3;
CREATE TABLE TABLE3
(
    ID               INT PRIMARY KEY,
    COLUMN_CHAR      CHAR(10),
    COLUMN_VARCHAR   VARCHAR(100),
    COLUMN_NUMBER    DECIMAL,
    COLUMN_DATE      DATE,
    COLUMN_TIMESTAMP TIMESTAMP
);
